name: Terraform Validate

on:
  workflow_dispatch:

  push:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-validate.yml"

  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform-validate.yml"

jobs:
  validate-dev:
    name: Validate Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

  validate-prod:
    name: Validate Prod
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate